const listProducts=[
  {title:'Кабельная сборка TestFlex® TF50A-29M29M-01.00M',subtitle:'2.92мм вилка - 2.92мм вилка, 50 Ом, 40 ГГц',mnemonic:'TF50A-29M29M-01.00M',article:'118173',brand:'NKT PRO',cable:'Гибкий фазостабильный кабель',feature:'С защитой',diameter:'Ø6 мм / L= 1000 мм',image:window.NKT_IMAGES[12]},
  {title:'Кабельная сборка SUCOFLEX H+S SF550S/11PC24/21PC24/1000mm',subtitle:'2.4мм вилка - 2.4мм розетка, 50 Ом, 50 ГГц',mnemonic:'SF550S/11PC24/21PC24/1000mm',article:'85118943',brand:'H+S',cable:'Гибкий фазостабильный кабель',feature:'С защитой',diameter:'Ø6 мм / L= 1000 мм',image:window.NKT_IMAGES[9]},
  {title:'Кабельная сборка TestFlex® TF50A-29M29M-01.00M',subtitle:'2.92мм вилка - 2.92мм вилка, 50 Ом, 40 ГГц',mnemonic:'TF50A-29M29M-01.00M',article:'118173',brand:'NKT PRO',cable:'Гибкий фазостабильный кабель',feature:'С защитой',diameter:'Ø6 мм / L= 1000 мм',image:window.NKT_IMAGES[12]}
];
function listCard(p){return `<article class="product-card"><div class="card-main"><h3>${p.title}</h3><p class="card-subtitle">${p.subtitle}</p><div class="card-info"><img class="card-photo" src="${p.image}" alt="${p.title}"><dl><dt>Мнемоника</dt><dd><a href="#">${p.mnemonic}</a><img src="assets/icons/copy.svg?v=20260721-2" alt="Копировать"></dd><dt>Артикул</dt><dd>${p.article}<img src="assets/icons/copy.svg?v=20260721-2" alt="Копировать"></dd><dt>Код товара</dt><dd>${p.article}nkt</dd><dt>Бренд</dt><dd>${p.brand}</dd><dt>Кабель</dt><dd>${p.cable}</dd><dt>Особенности</dt><dd>${p.feature}</dd><dt>Диаметр, мм</dt><dd>${p.diameter}</dd></dl></div><button class="all-specs">Все характеристики⌄</button><button class="card-pdf">Документы PDF<img src="assets/icons/download.svg?v=20260721-2" alt="Скачать"></button></div><aside class="card-buy"><div class="card-price-head"><span>Кол.</span><span>За ед.</span><span>Сумма</span></div><div class="card-prices"><b>1</b><b>10000₽</b><b>100000₽</b><b>10</b><b>8000₽</b><b>80000₽</b><b>25</b><b>7000₽</b><b>175000₽</b><b>50</b><b>6500₽</b><b>325000₽</b></div><a href="#">Доступно к заказу</a><div class="quantity"><button>−</button><span>1</span><button>+</button></div><small>мин. заказ</small><button class="list-cart">В корзину</button><button class="list-compare">Сравнить</button></aside></article>`}
const listView=document.querySelector('#listView'),tableView=document.querySelector('#tableView'),tableActions=document.querySelector('.table-actions'),listControls=document.querySelector('.list-controls'),viewButtons=[...document.querySelectorAll('[data-view]')];
listView.innerHTML=listProducts.map(listCard).join('');
function setView(view){const list=view==='list';listView.hidden=!list;tableView.hidden=list;tableActions.hidden=list;listControls.hidden=!list;viewButtons.forEach(b=>b.classList.toggle('active',b.dataset.view===view))}
viewButtons.forEach(button=>button.addEventListener('click',()=>setView(button.dataset.view)));
listView.addEventListener('click',e=>{if(e.target.closest('.list-cart'))toast('Товар добавлен в корзину');if(e.target.closest('.list-compare'))toast('Товар добавлен к сравнению')});
document.querySelector('#applyFilter').onclick=()=>{const stock=document.querySelector('#inStock').checked;[...rows.children].forEach((r,i)=>r.hidden=stock&&i%3===0);toast('Фильтры применены')};document.querySelector('#clearFilter').onclick=()=>{document.querySelectorAll('.filters input').forEach((x,i)=>x.checked=i===0);[...rows.children].forEach(r=>r.hidden=false);toast('Фильтры очищены')};document.querySelector('#cartSelected').onclick=()=>toast('Выбранные товары добавлены в корзину');document.querySelector('#compareSelected').onclick=()=>toast('Товары добавлены к сравнению');rows.addEventListener('click',e=>{if(e.target.closest('.cart'))toast('Товар добавлен в корзину')});
