const products=[
['NKT Drive A1','NKT-A1-075','Преобразователи',.75,'220 В','Modbus RTU','IP20','-20…+60 °C','DIN-рейка',1],['NKT Drive A3','NKT-A3-220','Преобразователи',2.2,'380 В','Modbus RTU','IP20','-20…+60 °C','Панель',1],['NKT Drive M5','NKT-M5-550','Преобразователи',5.5,'380 В','EtherCAT','IP54','-40…+70 °C','Панель',0],['NKT Drive X7','NKT-X7-1100','Преобразователи',11,'380–480 В','PROFINET','IP65','-40…+70 °C','Настенный',1],['NKT Control C2','NKT-C2-16','Контроллеры',.24,'24 В DC','Ethernet/IP','IP20','-20…+60 °C','DIN-рейка',1],['NKT Control C4','NKT-C4-32','Контроллеры',.36,'24 В DC','PROFINET','IP54','-40…+70 °C','DIN-рейка',1],['NKT Control C8','NKT-C8-64','Контроллеры',.48,'24 В DC','EtherCAT','IP65','-40…+70 °C','Панель',0],['NKT I/O 16','NKT-IO-D16','Модули ввода-вывода',.12,'24 В DC','Modbus TCP','IP54','-20…+60 °C','DIN-рейка',1],['NKT I/O 32','NKT-IO-D32','Модули ввода-вывода',.18,'24 В DC','PROFINET','IP65','-40…+70 °C','DIN-рейка',0]
].map(([name,code,category,power,voltage,face,protection,temperature,mount,stock])=>({name,code,category,power,voltage,face,protection,temperature,mount,stock}));
const $=s=>document.querySelector(s),rows=$('#rows'),search=$('#search'),sort=$('#sort'),wrap=$('#tableWrap'),thumb=$('#thumb'),filters=[...document.querySelectorAll('.options input')],selected=new Set();
const vals=n=>filters.filter(i=>i.name===n&&i.checked).map(i=>i.value);const plural=n=>n%100>10&&n%100<20?'товаров':n%10===1?'товар':n%10>1&&n%10<5?'товара':'товаров';
function list(){let q=search.value.trim().toLowerCase(),c=vals('category'),p=vals('protection'),t=vals('temperature'),a=products.filter(x=>(!q||(x.name+' '+x.code+' '+x.category).toLowerCase().includes(q))&&(!c.length||c.includes(x.category))&&(!p.length||p.includes(x.protection))&&(!t.length||t.includes(x.temperature)));if(sort.value==='name')a.sort((x,y)=>x.name.localeCompare(y.name,'ru'));if(sort.value==='power')a.sort((x,y)=>x.power-y.power);return a}
function render(){let a=list();$('#results').textContent=`Найдено: ${a.length}`;rows.innerHTML=a.length?a.map(x=>`<tr><td class="sticky"><div class="product-cell"><input data-code="${x.code}" type="checkbox" aria-label="Выбрать ${x.name}" ${selected.has(x.code)?'checked':''}><span class="product-icon">NKT</span><span class="product-name"><strong>${x.name}</strong><span>${x.code}</span></span></div></td><td>${x.category}</td><td>${x.power} кВт</td><td>${x.voltage}</td><td>${x.face}</td><td>${x.protection}</td><td>${x.temperature}</td><td>${x.mount}</td><td><span class="status ${x.stock?'':'order'}">${x.stock?'В наличии':'Под заказ'}</span></td></tr>`).join(''):'<tr class="empty"><td colspan="9">По заданным параметрам ничего не найдено</td></tr>'}
function count(){let n=selected.size;$('#selectedCount').textContent=`${n} ${plural(n)} выбрано`;$('#compare').disabled=n<2}function scrollState(){let max=wrap.scrollWidth-wrap.clientWidth;thumb.style.left=`${(max?wrap.scrollLeft/max:0)*76}%`}
rows.addEventListener('change',e=>{if(!e.target.dataset.code)return;e.target.checked?selected.add(e.target.dataset.code):selected.delete(e.target.dataset.code);count()});[search,sort,...filters].forEach(x=>x.addEventListener(x===search?'input':'change',render));$('#reset').onclick=()=>{search.value='';sort.value='default';filters.forEach(x=>x.checked=false);render()};document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>wrap.scrollBy({left:b.dataset.dir==='right'?420:-420,behavior:'smooth'}));wrap.addEventListener('scroll',scrollState,{passive:true});$('#compare').onclick=()=>{let t=$('#toast');t.textContent=`Сравниваем ${selected.size} ${plural(selected.size)}`;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2000)};render();count();requestAnimationFrame(scrollState);
