const categories=['Бортовые кабельные сборки для КА','Миниатюрные СВЧ сборки','Экономичные для измерений ECOTEST','Фазостабильные кабельные сборки','Стандартные сборки для измерений','Гибкие СВЧ кабельные сборки','Мультикоаксиальные сборки','Гибкие сборки до 6 ГГц','Кабельные сборки Sucoform и Multiflex','Сборки для PIM измерений','Сборки для термовакуумных измерений','Сборки для систем ЦОС'];
document.querySelector('#categories').innerHTML=categories.map((x,i)=>`<a href="#"><img src="${window.NKT_IMAGES[i]}" alt=""><strong>${x}</strong></a>`).join('');
document.querySelector('#siteLogo').src=window.NKT_IMAGES[13];
const rows=document.querySelector('#productRows');
function row(i){return `<tr><td class="select-col"><input class="pick" type="checkbox" ${i%4===0?'checked':''}></td><td class="name-col sticky"><strong>Кабельная сборка TestFlex®<br>TF50A-29M29M-01.00M</strong><small>Мнемоника</small><a href="#">TF50A-29M29M-01.00M　▣</a><small>Артикул</small><b>118173　▣</b></td><td class="photo-col"><img src="${window.NKT_IMAGES[12]}" alt="Кабельная сборка"></td><td class="desc-col">2.92мм вилка -<br>2.92мм вилка,<br>50 Ом, 40 ГГц<br><button class="pdf">PDF　♧</button></td><td class="price-col"><div class="price-head">Кол.　　За ед.　　Сумма</div><div class="prices"><b>1</b><b>10000₽</b><b>100000₽</b><b>10</b><b>8000₽</b><b>80000₽</b><b>25</b><b>7000₽</b><b>175000₽</b><b>50</b><b>6500₽</b><b>325000₽</b></div><a href="#">Доступно к заказу</a></td><td class="buy-col"><input type="number" value="1" min="1"><small>Миним.<br>заказ</small><button class="cart" aria-label="Добавить в корзину"><span class="cart-icon"></span></button></td><td class="brand-col">NKT PRO</td></tr>`}
rows.innerHTML=Array.from({length:8},(_,i)=>row(i)).join('');
const scroll=document.querySelector('#tableScroll'),thumb=document.querySelector('#topThumb');function update(){const max=scroll.scrollWidth-scroll.clientWidth;thumb.style.left=`${(max?scroll.scrollLeft/max:0)*68}%`}scroll.addEventListener('scroll',update,{passive:true});requestAnimationFrame(update);
function toast(text){const t=document.querySelector('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
document.querySelector('#applyFilter').onclick=()=>{const stock=document.querySelector('#inStock').checked;[...rows.children].forEach((r,i)=>r.hidden=stock&&i%3===0);toast('Фильтры применены')};document.querySelector('#clearFilter').onclick=()=>{document.querySelectorAll('.filters input').forEach((x,i)=>x.checked=i===0);[...rows.children].forEach(r=>r.hidden=false);toast('Фильтры очищены')};document.querySelector('#cartSelected').onclick=()=>toast('Выбранные товары добавлены в корзину');document.querySelector('#compareSelected').onclick=()=>toast('Товары добавлены к сравнению');rows.addEventListener('click',e=>{if(e.target.closest('.cart'))toast('Товар добавлен в корзину')});
