// Сгенерировано из файла «Список номенклатуры - Eu_HS -Разделен.xlsx».
window.NKT_CATALOG={
  "connectors": [
    {
      "id": "eupen-nm50b12x-m9",
      "article": null,
      "name": "NM50B12X",
      "manufacturer": "Eupen",
      "type": "N",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M9",
      "image": "../assets/configurator/connectors/eupen/n-male-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-nf50b12x-m9",
      "article": null,
      "name": "NF50B12X",
      "manufacturer": "Eupen",
      "type": "N",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M9",
      "image": "../assets/configurator/connectors/eupen/n-female-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-43mb12x-m9",
      "article": null,
      "name": "43MB12X",
      "manufacturer": "Eupen",
      "type": "4.3-10",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M9",
      "image": "../assets/configurator/connectors/eupen/43-10-male-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-43fb12x-m9",
      "article": null,
      "name": "43FB12X",
      "manufacturer": "Eupen",
      "type": "4.3-10",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M9",
      "image": "../assets/configurator/connectors/eupen/43-10-female-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-716mb12x-m9",
      "article": null,
      "name": "716MB12X",
      "manufacturer": "Eupen",
      "type": "7-16",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M9",
      "image": "../assets/configurator/connectors/eupen/7-16-male-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-716fb12x-m9",
      "article": null,
      "name": "716FB12X",
      "manufacturer": "Eupen",
      "type": "7-16",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M9",
      "image": "../assets/configurator/connectors/eupen/7-16-female-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-nm50v12-m12",
      "article": null,
      "name": "NM50V12",
      "manufacturer": "Eupen",
      "type": "N",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M12",
      "image": "../assets/configurator/connectors/eupen/n-male-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-nf50v12-m12",
      "article": null,
      "name": "NF50V12",
      "manufacturer": "Eupen",
      "type": "N",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M12",
      "image": "../assets/configurator/connectors/eupen/n-female-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-43mv12n1-m12",
      "article": null,
      "name": "43MV12N1",
      "manufacturer": "Eupen",
      "type": "4.3-10",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M12",
      "image": "../assets/configurator/connectors/eupen/43-10-male-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-43fv12n1-m12",
      "article": null,
      "name": "43FV12N1",
      "manufacturer": "Eupen",
      "type": "4.3-10",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M12",
      "image": "../assets/configurator/connectors/eupen/43-10-female-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-716mv12n1-m12",
      "article": null,
      "name": "716MV12N1",
      "manufacturer": "Eupen",
      "type": "7-16",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M12",
      "image": "../assets/configurator/connectors/eupen/7-16-male-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-716fv12n1-m12",
      "article": null,
      "name": "716FV12N1",
      "manufacturer": "Eupen",
      "type": "7-16",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M12",
      "image": "../assets/configurator/connectors/eupen/7-16-female-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-nm50vl12-m12",
      "article": null,
      "name": "NM50VL12",
      "manufacturer": "Eupen",
      "type": "N",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Сборка",
      "group": "M12",
      "image": "../assets/configurator/connectors/eupen/n-male-right-angle-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-716mvl12-m12",
      "article": null,
      "name": "716MVL12",
      "manufacturer": "Eupen",
      "type": "N",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Сборка",
      "group": "M12",
      "image": "../assets/configurator/connectors/eupen/n-male-right-angle-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-nm50v78n1-m25",
      "article": null,
      "name": "NM50V78N1",
      "manufacturer": "Eupen",
      "type": "N",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M25",
      "image": "../assets/configurator/connectors/eupen/n-male-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-nf50v78n1-m25",
      "article": null,
      "name": "NF50V78N1",
      "manufacturer": "Eupen",
      "type": "N",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M25",
      "image": "../assets/configurator/connectors/eupen/n-female-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-43mv78n1-m25",
      "article": null,
      "name": "43MV78N1",
      "manufacturer": "Eupen",
      "type": "4.3-10",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M25",
      "image": "../assets/configurator/connectors/eupen/43-10-male-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-43fv78n1-m25",
      "article": null,
      "name": "43FV78N1",
      "manufacturer": "Eupen",
      "type": "4.3-10",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M25",
      "image": "../assets/configurator/connectors/eupen/43-10-female-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-716mv78n1-m25",
      "article": null,
      "name": "716MV78N1",
      "manufacturer": "Eupen",
      "type": "7-16",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M25",
      "image": "../assets/configurator/connectors/eupen/7-16-male-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-716fv78n1-m25",
      "article": null,
      "name": "716FV78N1",
      "manufacturer": "Eupen",
      "type": "7-16",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M25",
      "image": "../assets/configurator/connectors/eupen/7-16-female-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-nm50v114n1-m32",
      "article": null,
      "name": "NM50V114N1",
      "manufacturer": "Eupen",
      "type": "N",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M32",
      "image": "../assets/configurator/connectors/eupen/n-male-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-nf50v114n1-m32",
      "article": null,
      "name": "NF50V114N1",
      "manufacturer": "Eupen",
      "type": "N",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M32",
      "image": "../assets/configurator/connectors/eupen/n-female-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-43fv114n1-m32",
      "article": null,
      "name": "43FV114N1",
      "manufacturer": "Eupen",
      "type": "4.3-10",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M32",
      "image": "../assets/configurator/connectors/eupen/43-10-female-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-716mv114n1-m32",
      "article": null,
      "name": "716MV114N1",
      "manufacturer": "Eupen",
      "type": "7-16",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M32",
      "image": "../assets/configurator/connectors/eupen/7-16-male-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-716fv114n1-m32",
      "article": null,
      "name": "716FV114N1",
      "manufacturer": "Eupen",
      "type": "7-16",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M32",
      "image": "../assets/configurator/connectors/eupen/7-16-female-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-nm50v158n1-m42",
      "article": null,
      "name": "NM50V158N1",
      "manufacturer": "Eupen",
      "type": "N",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M42",
      "image": "../assets/configurator/connectors/eupen/n-male-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-nf50v158n1-m42",
      "article": null,
      "name": "NF50V158N1",
      "manufacturer": "Eupen",
      "type": "N",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M42",
      "image": "../assets/configurator/connectors/eupen/n-female-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-43fv158n1-m42",
      "article": null,
      "name": "43FV158N1",
      "manufacturer": "Eupen",
      "type": "4.3-10",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M42",
      "image": "../assets/configurator/connectors/eupen/43-10-female-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-716mv158n1-m42",
      "article": null,
      "name": "716MV158N1",
      "manufacturer": "Eupen",
      "type": "7-16",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M42",
      "image": "../assets/configurator/connectors/eupen/7-16-male-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "eupen-716fv158n1-m42",
      "article": null,
      "name": "716FV158N1",
      "manufacturer": "Eupen",
      "type": "7-16",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M42",
      "image": "../assets/configurator/connectors/eupen/7-16-female-straight-assembly.png",
      "massGrams": null
    },
    {
      "id": "hs-11-n-50-3-64-133-ne-x27",
      "article": "85018524",
      "name": "11 N-50-3-64/133 NE",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "X27",
      "image": "../assets/configurator/connectors/hs/n-male-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-n-50-3-70-133-ne-x27",
      "article": "85069731",
      "name": "16 N-50-3-70/133 NE",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Пайка + обжим",
      "group": "X27",
      "image": "../assets/configurator/connectors/hs/n-male-right-angle-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-n-50-3-22-133-nh-x27",
      "article": "85070105",
      "name": "21 N-50-3-22/133 NH",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "X27",
      "image": "../assets/configurator/connectors/hs/n-female-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-24-n-50-3-45-133-nh-x27",
      "article": "85070117",
      "name": "24 N-50-3-45/133 NH",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "female",
      "shape": "Панельный",
      "mount": "Обжим",
      "group": "X27",
      "image": "../assets/configurator/connectors/hs/n-female-panel-crimp.png",
      "massGrams": null
    },
    {
      "id": "hs-11-sma-50-3-239-133-ne-x27",
      "article": "85010668",
      "name": "11 SMA-50-3-239/133 NE",
      "manufacturer": "H+S",
      "type": "SMA",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "X27",
      "image": "../assets/configurator/connectors/hs/sma-male-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-sma-50-3-239-133-ne-x27",
      "article": "85018510",
      "name": "16 SMA-50-3-239/133 NE",
      "manufacturer": "H+S",
      "type": "SMA",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Пайка + обжим",
      "group": "X27",
      "image": "../assets/configurator/connectors/hs/sma-male-right-angle-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-tnc-50-3-120-133-ne-x27",
      "article": "85010745",
      "name": "11 TNC-50-3-120/133 NE",
      "manufacturer": "H+S",
      "type": "TNC",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "X27",
      "image": "../assets/configurator/connectors/hs/tnc-male-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-24-tnc-50-3-54-133-ne-x27",
      "article": "85010762",
      "name": "24 TNC-50-3-54/133 NE",
      "manufacturer": "H+S",
      "type": "TNC",
      "gender": "female",
      "shape": "Панельный",
      "mount": "Обжим",
      "group": "X27",
      "image": "../assets/configurator/connectors/hs/tnc-female-panel-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-tnc-50-4-77-133-ne-x28",
      "article": "85010169",
      "name": "11 TNC-50-4-77/133 NE",
      "manufacturer": "H+S",
      "type": "TNC",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/tnc-male-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-24-tnc-50-4-77-133-ne-x28",
      "article": "85010236",
      "name": "24 TNC-50-4-77/133 NE",
      "manufacturer": "H+S",
      "type": "TNC",
      "gender": "female",
      "shape": "Панельный",
      "mount": "Обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/tnc-female-panel-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-tnc-50-4-16-133-ne-x28",
      "article": "84119563",
      "name": "21 TNC-50-4-16/133 NE",
      "manufacturer": "H+S",
      "type": "TNC",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/tnc-female-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-tnc-50-4-78-133-ne-x28",
      "article": "85071433",
      "name": "11 TNC-50-4-78/133 NE",
      "manufacturer": "H+S",
      "type": "TNC",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/tnc-male-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-tnc-50-4-18-133-ne-x28",
      "article": "85159704",
      "name": "21 TNC-50-4-18/133 NE",
      "manufacturer": "H+S",
      "type": "TNC",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/tnc-female-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-tnc-50-4-22-133-ne-x28",
      "article": "85071590",
      "name": "16 TNC-50-4-22/133 NE",
      "manufacturer": "H+S",
      "type": "TNC",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Пайка + обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/tnc-male-right-angle-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-bnc-50-4-28-133-ne-x28",
      "article": "22660156",
      "name": "11 BNC-50-4-28/133 NE",
      "manufacturer": "H+S",
      "type": "BNC",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/bnc-male-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-bnc-50-4-29-133-ne-x28",
      "article": "84068115",
      "name": "11 BNC-50-4-29/133 NE",
      "manufacturer": "H+S",
      "type": "BNC",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/bnc-male-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-24-bnc-50-4-10-133-ne-x28",
      "article": "85071247",
      "name": "24 BNC-50-4-10/133 NE",
      "manufacturer": "H+S",
      "type": "BNC",
      "gender": "female",
      "shape": "Панельный",
      "mount": "Обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/bnc-female-panel-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-bnc-50-4-16-133-nh-x28",
      "article": "85071464",
      "name": "16 BNC-50-4-16/133 NH",
      "manufacturer": "H+S",
      "type": "BNC",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Пайка + обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/bnc-male-right-angle-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-24-n-50-4-10-133-ne-x28",
      "article": "85018527",
      "name": "24 N-50-4-10/133 NE",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "female",
      "shape": "Панельный",
      "mount": "Обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/n-female-panel-crimp.png",
      "massGrams": null
    },
    {
      "id": "hs-16-n-50-4-121-133-ne-x28",
      "article": "85157254",
      "name": "16 N-50-4-121/133 NE",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Пайка + обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/n-male-right-angle-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-n-50-4-11-133-ne-x28",
      "article": "85153529",
      "name": "21 N-50-4-11/133 NE",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/n-female-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-n-50-4-72-133-ne-x28",
      "article": "85128376",
      "name": "11 N-50-4-72/133 NE",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/n-male-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-qma-50-4-2-133-nh-x28",
      "article": "23041666",
      "name": "16 QMA-50-4-2/133 NH",
      "manufacturer": "H+S",
      "type": "QMA",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Пайка + обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/qma-male-right-angle-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-qma-50-4-2-133-nh-x28",
      "article": "84096247",
      "name": "21 QMA-50-4-2/133 NH",
      "manufacturer": "H+S",
      "type": "QMA",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Пайка + обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/qma-female-straight-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-qma-w50-4-5-133-ne-x28",
      "article": "84075864",
      "name": "16 QMA-W50-4-5/133 NE",
      "manufacturer": "H+S",
      "type": "QMA",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Пайка + обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/qma-male-right-angle-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-qma-50-4-2-133-ne-x28",
      "article": "85123653",
      "name": "16 QMA-50-4-2/133 NE",
      "manufacturer": "H+S",
      "type": "QMA",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Пайка + обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/qma-male-right-angle-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-qma-w50-4-3-133-ne-x28",
      "article": "84075865",
      "name": "11 QMA-W50-4-3/133 NE",
      "manufacturer": "H+S",
      "type": "QMA",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Пайка + обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/qma-male-straight-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-qma-50-4-2-133-ne-x28",
      "article": "85123642",
      "name": "11 QMA-50-4-2/133 NE",
      "manufacturer": "H+S",
      "type": "QMA",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Пайка + обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/qma-male-straight-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-4310-50-4-x1-033-h-x28",
      "article": "85078855",
      "name": "11 4310-50-4-X1/033 -H",
      "manufacturer": "H+S",
      "type": "4.3-10",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/43-10-male-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-716-50-4-5-033-y-x28",
      "article": "84098543",
      "name": "11 716-50-4-5/033 -Y",
      "manufacturer": "H+S",
      "type": "7-16",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/7-16-male-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-tnc-50-7-18-133-ne-u30",
      "article": "84077868",
      "name": "11 TNC-50-7-18/133 NE",
      "manufacturer": "H+S",
      "type": "TNC",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/tnc-male-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-tnc-50-7-19-133-ne-u30",
      "article": "85016678",
      "name": "11 TNC-50-7-19/133 NE",
      "manufacturer": "H+S",
      "type": "TNC",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/tnc-male-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-tnc-50-7-12-133-ne-u30",
      "article": "84082741",
      "name": "16 TNC-50-7-12/133 NE",
      "manufacturer": "H+S",
      "type": "TNC",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Сборка",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/tnc-male-right-angle-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-tnc-50-7-17-133-ne-u30",
      "article": "84084333",
      "name": "16 TNC-50-7-17/133 NE",
      "manufacturer": "H+S",
      "type": "TNC",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Пайка + обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/tnc-male-right-angle-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-24-tnc-50-7-5-133-ne-u30",
      "article": "85018142",
      "name": "24 TNC-50-7-5/133 NE",
      "manufacturer": "H+S",
      "type": "TNC",
      "gender": "female",
      "shape": "Панельный",
      "mount": "Обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/tnc-female-panel-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-tnc-50-7-1-133-ne-u30",
      "article": "84128527",
      "name": "21 TNC-50-7-1/133 NE",
      "manufacturer": "H+S",
      "type": "TNC",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/tnc-female-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-sma-50-7-1-133-ne-u30",
      "article": "85018509",
      "name": "11 SMA-50-7-1/133 NE",
      "manufacturer": "H+S",
      "type": "SMA",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/sma-male-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-sma-50-7-1-133-ne-u30",
      "article": "85018517",
      "name": "16 SMA-50-7-1/133 NE",
      "manufacturer": "H+S",
      "type": "SMA",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Пайка + обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/sma-male-right-angle-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-bnc-50-7-13-133-ne-u30",
      "article": "85071256",
      "name": "11 BNC-50-7-13/133 NE",
      "manufacturer": "H+S",
      "type": "BNC",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/bnc-male-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-bnc-50-7-9-133-ne-u30",
      "article": "85071432",
      "name": "16 BNC-50-7-9/133 NE",
      "manufacturer": "H+S",
      "type": "BNC",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Пайка + обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/bnc-male-right-angle-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-n-50-7-77-133-nh-u30",
      "article": "84076005",
      "name": "16 N-50-7-77/133 NH",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Пайка + обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/n-male-right-angle-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-n-50-7-77-133-ne-u30",
      "article": "84078884",
      "name": "16 N-50-7-77/133 NE",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Пайка + обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/n-male-right-angle-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-n-50-7-50-133-ne-u30",
      "article": "84082125",
      "name": "16 N-50-7-50/133 NE",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Пайка + обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/n-male-right-angle-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-n-50-7-53-133-ne-u30",
      "article": "85014128",
      "name": "16 N-50-7-53/133 NE",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Пайка + обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/n-male-right-angle-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-24-n-50-7-31-133-ny-u30",
      "article": "84000974",
      "name": "24 N-50-7-31/133 NY",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "female",
      "shape": "Панельный",
      "mount": "Обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/n-female-panel-crimp.png",
      "massGrams": null
    },
    {
      "id": "hs-21-n-50-7-32-133-ne-u30",
      "article": "84119763",
      "name": "21 N-50-7-32/133 NE",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/n-female-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-n-50-7-69-133-ne-u30",
      "article": "22660143",
      "name": "11 N-50-7-69/133 NE",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/n-male-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-n-50-7-74-133-ue-1-u30",
      "article": "23041525",
      "name": "11 N-50-7-74/133 UE-1",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/n-male-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-qn-50-7-5-133-nh-u30",
      "article": "84022186",
      "name": "16 QN-50-7-5/133 NH",
      "manufacturer": "H+S",
      "type": "QN",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Пайка + обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/qn-male-right-angle-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-qn-50-7-5-133-ne-u30",
      "article": "84078879",
      "name": "16 QN-50-7-5/133 NE",
      "manufacturer": "H+S",
      "type": "QN",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Пайка + обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/qn-male-right-angle-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-24-qn-50-7-5-133-nh-u30",
      "article": "84039869",
      "name": "24 QN-50-7-5/133 NH",
      "manufacturer": "H+S",
      "type": "QN",
      "gender": "female",
      "shape": "Панельный",
      "mount": "Пайка + обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/qn-female-panel-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-qn-50-7-8-133-nh-u30",
      "article": "84022686",
      "name": "11 QN-50-7-8/133 NH",
      "manufacturer": "H+S",
      "type": "QN",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Пайка + обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/qn-male-straight-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-qn-50-7-8-133-ne-u30",
      "article": "84078850",
      "name": "11 QN-50-7-8/133 NE",
      "manufacturer": "H+S",
      "type": "QN",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Пайка + обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/qn-male-straight-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-716-50-7-15-033-e-u30",
      "article": "23025134",
      "name": "16 716-50-7-15/033 -E",
      "manufacturer": "H+S",
      "type": "7-16",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Пайка + обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/7-16-male-right-angle-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-716-50-7-31-033-y-u30",
      "article": "85010777",
      "name": "11 716-50-7-31/033 -Y",
      "manufacturer": "H+S",
      "type": "7-16",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/7-16-male-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-4310-50-7-x2-033-e-u30",
      "article": "85141072",
      "name": "11 4310-50-7-X2/033 -E",
      "manufacturer": "H+S",
      "type": "4.3-10",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "U30",
      "image": "../assets/configurator/connectors/hs/43-10-male-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-n-50-12-20-033-e-x29",
      "article": "85009711",
      "name": "11 N-50-12-20/033 -E",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "X29",
      "image": "../assets/configurator/connectors/hs/n-male-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-n-50-12-12-033-e-x29",
      "article": "85018526",
      "name": "16 N-50-12-12/033 -E",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Обжим",
      "group": "X29",
      "image": "../assets/configurator/connector-placeholder.svg",
      "massGrams": null
    },
    {
      "id": "hs-11-716-50-12-8-033-y-x29",
      "article": "85018507",
      "name": "11 716-50-12-8/033 -Y",
      "manufacturer": "H+S",
      "type": "7-16",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "X29",
      "image": "../assets/configurator/connectors/hs/7-16-male-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-n-50-9-12-033-f-x31",
      "article": "85032688",
      "name": "11 N-50-9-12/033 -F",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "X31",
      "image": "../assets/configurator/connectors/hs/n-male-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-n-50-9-11-033-f-x31",
      "article": "85032410",
      "name": "21 N-50-9-11/033 -F",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "X31",
      "image": "../assets/configurator/connectors/hs/n-female-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-24-n-50-9-36-033-f-x31",
      "article": "85143441",
      "name": "24 N-50-9-36/033 -F",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "female",
      "shape": "Панельный",
      "mount": "Обжим",
      "group": "X31",
      "image": "../assets/configurator/connectors/hs/n-female-panel-crimp.png",
      "massGrams": null
    },
    {
      "id": "hs-16-n-50-9-8-133-nv-x31",
      "article": "85075501",
      "name": "16 N-50-9-8/133 NV",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Пайка + обжим",
      "group": "X31",
      "image": "../assets/configurator/connectors/hs/n-male-right-angle-solder.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-qn-50-9-1-133-ne-x31",
      "article": "85101069",
      "name": "11 QN-50-9-1/133 NE",
      "manufacturer": "H+S",
      "type": "QN",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "X31",
      "image": "../assets/configurator/connectors/hs/qn-male-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-n-50-9-9-033-e-m9",
      "article": "22660311",
      "name": "11 N-50-9-9/033 -E",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M9",
      "image": "../assets/configurator/connectors/hs/n-male-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-n-50-9-9-033-e-m9",
      "article": "22660312",
      "name": "21 N-50-9-9/033 -E",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M9",
      "image": "../assets/configurator/connectors/hs/n-female-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-n-50-9-6-033-e-m9",
      "article": "23007299",
      "name": "16 N-50-9-6/033 -E",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Сборка",
      "group": "M9",
      "image": "../assets/configurator/connectors/hs/n-male-right-angle-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-716-50-9-9-033-e-m9",
      "article": "22660309",
      "name": "11 716-50-9-9/033 -E",
      "manufacturer": "H+S",
      "type": "7-16",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M9",
      "image": "../assets/configurator/connectors/hs/7-16-male-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-716-50-9-9-033-e-m9",
      "article": "22660310",
      "name": "21 716-50-9-9/033 -E",
      "manufacturer": "H+S",
      "type": "7-16",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M9",
      "image": "../assets/configurator/connectors/hs/7-16-female-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-716-50-9-5-033-e-m9",
      "article": "23007298",
      "name": "16 716-50-9-5/033 -E",
      "manufacturer": "H+S",
      "type": "7-16",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Сборка",
      "group": "M9",
      "image": "../assets/configurator/connectors/hs/7-16-male-right-angle-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-4310-50-9-x2-033-e-m9",
      "article": "85068623",
      "name": "11 4310-50-9-X2/033 -E",
      "manufacturer": "H+S",
      "type": "4.3-10",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M9",
      "image": "../assets/configurator/connectors/hs/43-10-male-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-4310-50-9-x1-033-e-m9",
      "article": "85068620",
      "name": "16 4310-50-9-X1/033 -E",
      "manufacturer": "H+S",
      "type": "4.3-10",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Сборка",
      "group": "M9",
      "image": "../assets/configurator/connectors/hs/43-10-male-right-angle-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-n-50-12-50-033-e-m12",
      "article": "84201169",
      "name": "11 N-50-12-50/033 -E",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M12",
      "image": "../assets/configurator/connectors/hs/n-male-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-n-50-12-50-033-e-m12",
      "article": "84201173",
      "name": "21 N-50-12-50/033 -E",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M12",
      "image": "../assets/configurator/connectors/hs/n-female-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-4310-50-12-z60-033-e-m12",
      "article": "85074830",
      "name": "16 4310-50-12-Z60/033 -E",
      "manufacturer": "H+S",
      "type": "4.3-10",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Сборка",
      "group": "M12",
      "image": "../assets/configurator/connectors/hs/43-10-male-right-angle-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-4310-50-12-1-033-e-m12",
      "article": "85029736",
      "name": "21 4310-50-12-1/033 -E",
      "manufacturer": "H+S",
      "type": "4.3-10",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M12",
      "image": "../assets/configurator/connectors/hs/43-10-female-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-n-50-23-43-033-e-m23",
      "article": "84124063",
      "name": "11 N-50-23-43/033 -E",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M23",
      "image": "../assets/configurator/connectors/hs/n-male-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-n-50-23-43-033-e-m23",
      "article": "84124062",
      "name": "21 N-50-23-43/033 -E",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M23",
      "image": "../assets/configurator/connectors/hs/n-female-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-716-50-23-44-033-e-m23",
      "article": "84069135",
      "name": "11 716-50-23-44/033 -E",
      "manufacturer": "H+S",
      "type": "7-16",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M23",
      "image": "../assets/configurator/connectors/hs/7-16-male-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-716-50-23-44-033-e-m23",
      "article": "84069194",
      "name": "21 716-50-23-44/033 -E",
      "manufacturer": "H+S",
      "type": "7-16",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M23",
      "image": "../assets/configurator/connectors/hs/7-16-female-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-4310-50-23-x1-033-e-m23",
      "article": "85076926",
      "name": "11 4310-50-23-X1/033 -E",
      "manufacturer": "H+S",
      "type": "4.3-10",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M23",
      "image": "../assets/configurator/connectors/hs/43-10-male-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-4310-50-23-1-003-e-m23",
      "article": "85076927",
      "name": "21 4310-50-23-1/003 -E",
      "manufacturer": "H+S",
      "type": "4.3-10",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M23",
      "image": "../assets/configurator/connectors/hs/43-10-female-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-n-50-23-43-033-e-m24",
      "article": "84124063",
      "name": "11 N-50-23-43/033 -E",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M24",
      "image": "../assets/configurator/connectors/hs/n-male-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-n-50-23-43-033-e-m24",
      "article": "84124062",
      "name": "21 N-50-23-43/033 -E",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M24",
      "image": "../assets/configurator/connectors/hs/n-female-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-716-50-23-44-033-e-m24",
      "article": "84069135",
      "name": "11 716-50-23-44/033 -E",
      "manufacturer": "H+S",
      "type": "7-16",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M24",
      "image": "../assets/configurator/connectors/hs/7-16-male-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-716-50-23-44-033-e-m24",
      "article": "84069194",
      "name": "21 716-50-23-44/033 -E",
      "manufacturer": "H+S",
      "type": "7-16",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M24",
      "image": "../assets/configurator/connectors/hs/7-16-female-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-4310-50-23-x1-033-e-m24",
      "article": "85076926",
      "name": "11 4310-50-23-X1/033 -E",
      "manufacturer": "H+S",
      "type": "4.3-10",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M24",
      "image": "../assets/configurator/connectors/hs/43-10-male-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-4310-50-23-1-003-e-m24",
      "article": "85076927",
      "name": "21 4310-50-23-1/003 -E",
      "manufacturer": "H+S",
      "type": "4.3-10",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M24",
      "image": "../assets/configurator/connectors/hs/43-10-female-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-716-50-32-4-033-e-m32",
      "article": "84116150",
      "name": "21 716-50-32-4/033 -E",
      "manufacturer": "H+S",
      "type": "7-16",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M32",
      "image": "../assets/configurator/connectors/hs/7-16-female-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-4310-50-32-x1-033-e-m32",
      "article": "85238346",
      "name": "11 4310-50-32-X1/033 -E",
      "manufacturer": "H+S",
      "type": "4.3-10",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M32",
      "image": "../assets/configurator/connectors/hs/43-10-male-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-716-50-42-4-033-e-m42",
      "article": "84079305",
      "name": "21 716-50-42-4/033 -E",
      "manufacturer": "H+S",
      "type": "7-16",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M42",
      "image": "../assets/configurator/connectors/hs/7-16-female-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-716-50-5-4-003-z-m5",
      "article": "23003412",
      "name": "11 716-50-5-4/003 -Z",
      "manufacturer": "H+S",
      "type": "7-16",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M5",
      "image": "../assets/configurator/connectors/hs/7-16-male-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-16-716-50-5-2-003-z-m5",
      "article": "23016774",
      "name": "16 716-50-5-2/003 -Z",
      "manufacturer": "H+S",
      "type": "7-16",
      "gender": "male",
      "shape": "Угловой",
      "mount": "Сборка",
      "group": "M5",
      "image": "../assets/configurator/connectors/hs/7-16-male-right-angle-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-n-50-5-400-103-uy-m5",
      "article": "23011948",
      "name": "11 N-50-5-400/103 UY",
      "manufacturer": "H+S",
      "type": "N",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Сборка",
      "group": "M5",
      "image": "../assets/configurator/connectors/hs/n-male-straight-assembly.webp",
      "massGrams": null
    },
    {
      "id": "hs-11-qn-50-5-2-133-nh-m5",
      "article": "84022712",
      "name": "11 QN-50-5-2/133 NH",
      "manufacturer": "H+S",
      "type": "QN",
      "gender": "male",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "M5",
      "image": "../assets/configurator/connectors/hs/qn-male-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-sma-50-3-23-133-ne-x27",
      "article": "85269219",
      "name": "21 SMA-50-3-23/133 NE",
      "manufacturer": "H+S",
      "type": "SMA",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "X27",
      "image": "../assets/configurator/connectors/hs/sma-female-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-sma-50-4-52-133-ne-x9",
      "article": "22644409",
      "name": "21 SMA-50-4-52/133 NE",
      "manufacturer": "H+S",
      "type": "SMA",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "X9",
      "image": "../assets/configurator/connectors/hs/sma-female-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "hs-21-sma-50-4-52-133-ne-x28",
      "article": "22644409",
      "name": "21 SMA-50-4-52/133 NE",
      "manufacturer": "H+S",
      "type": "SMA",
      "gender": "female",
      "shape": "Прямой",
      "mount": "Обжим",
      "group": "X28",
      "image": "../assets/configurator/connectors/hs/sma-female-straight-crimp.webp",
      "massGrams": null
    },
    {
      "id": "OPEN",
      "article": null,
      "name": "Без разъёма — открытый конец",
      "manufacturer": "НКТ",
      "type": "OPEN",
      "gender": "none",
      "shape": "Открытый конец",
      "mount": "—",
      "group": "*",
      "image": "../assets/configurator/connector-placeholder.svg",
      "massGrams": 0
    }
  ],
  "cables": [
    {
      "id": "cable-ec4-50",
      "article": null,
      "name": "EC4-50",
      "manufacturer": "Eupen",
      "size": "1/2\"",
      "group": "M12",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-ec4-50-frc",
      "article": null,
      "name": "EC4-50-FRC",
      "manufacturer": "Eupen",
      "size": "1/2\"",
      "group": "M12",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-ec4-50-hf",
      "article": null,
      "name": "EC4-50-HF",
      "manufacturer": "Eupen",
      "size": "1/2\" Highflex",
      "group": "M9",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-ec4-50-hf-frb",
      "article": null,
      "name": "EC4-50-HF-FRB",
      "manufacturer": "Eupen",
      "size": "1/2\" Highflex",
      "group": "M9",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-ec5-50-a",
      "article": null,
      "name": "EC5-50-A",
      "manufacturer": "Eupen",
      "size": "7/8\"",
      "group": "M25",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-ec5-50-a-frc",
      "article": null,
      "name": "EC5-50-A-FRC",
      "manufacturer": "Eupen",
      "size": "7/8\"",
      "group": "M25",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-ec6-50-a",
      "article": null,
      "name": "EC6-50-A",
      "manufacturer": "Eupen",
      "size": "1 1/4\"",
      "group": "M32",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-ec6-50-a-frc",
      "article": null,
      "name": "EC6-50-A-FRC",
      "manufacturer": "Eupen",
      "size": "1 1/4\"",
      "group": "M32",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-ec7-50-a",
      "article": null,
      "name": "EC7-50-A",
      "manufacturer": "Eupen",
      "size": "1 5/8\"",
      "group": "M42",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-ec7-50-a-frc",
      "article": null,
      "name": "EC7-50-A-FRC",
      "manufacturer": "Eupen",
      "size": "1 5/8\"",
      "group": "M42",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-ec400",
      "article": null,
      "name": "EC400+",
      "manufacturer": "Eupen",
      "size": "10,25 mm",
      "group": "U30",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-ec400-hlfr",
      "article": null,
      "name": "EC400-HLFR",
      "manufacturer": "Eupen",
      "size": "10,25 mm",
      "group": "U30",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-spuma-195",
      "article": "84151727",
      "name": "SPUMA 195",
      "manufacturer": "H+S",
      "size": "5 mm",
      "group": "X27",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-spuma-195-fr-01",
      "article": "85021562",
      "name": "SPUMA 195-FR-01",
      "manufacturer": "H+S",
      "size": "5 mm",
      "group": "X27",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-spuma-195-fr-am",
      "article": "85069658",
      "name": "SPUMA 195-FR-AM",
      "manufacturer": "H+S",
      "size": "5 mm",
      "group": "X27",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-spuma-240",
      "article": "84151737",
      "name": "SPUMA 240",
      "manufacturer": "H+S",
      "size": "6,15 mm",
      "group": "X28",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-spuma-240-fr-01",
      "article": "85021563",
      "name": "SPUMA 240-FR-01",
      "manufacturer": "H+S",
      "size": "6,15 mm",
      "group": "X28",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-spuma-240-fr-am",
      "article": "85069656",
      "name": "SPUMA 240-FR-AM",
      "manufacturer": "H+S",
      "size": "6,15 mm",
      "group": "X28",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-spuma-240-rs-fr",
      "article": "85089188",
      "name": "SPUMA 240-RS-FR",
      "manufacturer": "H+S",
      "size": "6,15 mm",
      "group": "X28",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-spuma-400",
      "article": "84102703",
      "name": "SPUMA 400",
      "manufacturer": "H+S",
      "size": "10,25 mm",
      "group": "U30",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-spuma-400-fr",
      "article": "84040210",
      "name": "SPUMA 400-FR",
      "manufacturer": "H+S",
      "size": "10,25 mm",
      "group": "U30",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-spuma-400-fr-01",
      "article": "84132035",
      "name": "SPUMA 400-FR-01",
      "manufacturer": "H+S",
      "size": "10,25 mm",
      "group": "U30",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-spuma-400-fr-75",
      "article": "85022187",
      "name": "SPUMA 400-FR-75",
      "manufacturer": "H+S",
      "size": "10,25 mm",
      "group": "U30",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-spuma-400-rs-fr",
      "article": "85089191",
      "name": "SPUMA 400-RS-FR",
      "manufacturer": "H+S",
      "size": "10,25 mm",
      "group": "U30",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-spuma-500-fr-01",
      "article": "85021564",
      "name": "SPUMA 500-FR-01",
      "manufacturer": "H+S",
      "size": "12,78 mm",
      "group": "X31",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-spuma-600",
      "article": "84151738",
      "name": "SPUMA 600",
      "manufacturer": "H+S",
      "size": "15 mm",
      "group": "X29",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-spuma-600-rs-fr",
      "article": "85240547",
      "name": "SPUMA 600-RS-FR",
      "manufacturer": "H+S",
      "size": "15 mm",
      "group": "X29",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-sucofeed-1-4-hf",
      "article": "84020854",
      "name": "SUCOFEED 1/4 HF",
      "manufacturer": "H+S",
      "size": "1/4\" Highflex",
      "group": "M5",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-sucofeed-1-4-hf-fr",
      "article": "84020855",
      "name": "SUCOFEED 1/4 HF FR",
      "manufacturer": "H+S",
      "size": "1/4\" Highflex",
      "group": "M5",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-sucofeed-3-8-hf-a",
      "article": "84020856",
      "name": "SUCOFEED 3/8 HF A",
      "manufacturer": "H+S",
      "size": "3/8\" Highflex",
      "group": "M7",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-sucofeed-3-8-hf-fr-a",
      "article": "84020857",
      "name": "SUCOFEED 3/8 HF FR A",
      "manufacturer": "H+S",
      "size": "3/8\" Highflex",
      "group": "M7",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-sucofeed-1-2-hf",
      "article": "84099336",
      "name": "SUCOFEED 1/2 HF",
      "manufacturer": "H+S",
      "size": "1/2\" Highflex",
      "group": "M9",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-sucofeed-1-2-hf-fr",
      "article": "84020859",
      "name": "SUCOFEED 1/2 HF FR",
      "manufacturer": "H+S",
      "size": "1/2\" Highflex",
      "group": "M9",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-sucofeed-1-2",
      "article": "84099352",
      "name": "SUCOFEED 1/2",
      "manufacturer": "H+S",
      "size": "1/2\"",
      "group": "M12",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-sucofeed-1-2-fr",
      "article": "84020848",
      "name": "SUCOFEED 1/2 FR",
      "manufacturer": "H+S",
      "size": "1/2\"",
      "group": "M12",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-sucofeed-7-8-la-a",
      "article": "84020851",
      "name": "SUCOFEED 7/8 LA A",
      "manufacturer": "H+S",
      "size": "7/8\"",
      "group": "M25",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-sucofeed-7-8-la-fr-a",
      "article": "84115695",
      "name": "SUCOFEED_7/8_LA_FR_A",
      "manufacturer": "H+S",
      "size": "7/8\"",
      "group": "M25",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-sucofeed-7-8",
      "article": "84020852",
      "name": "SUCOFEED_7/8",
      "manufacturer": "H+S",
      "size": "7/8\"",
      "group": "M23",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-sucofeed-7-8-fr",
      "article": "84020853",
      "name": "SUCOFEED 7/8 FR",
      "manufacturer": "H+S",
      "size": "7/8\"",
      "group": "M23",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-sucofeed-7-8-fr-hf",
      "article": "84008162",
      "name": "SUCOFEED 7/8 FR HF",
      "manufacturer": "H+S",
      "size": "7/8\"",
      "group": "M24",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-sucofeed-1-5-8",
      "article": "84020864",
      "name": "SUCOFEED 1 5/8",
      "manufacturer": "H+S",
      "size": "1 5/8\"",
      "group": "M42",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-sucofeed-1-1-4-fr",
      "article": "84020862",
      "name": "SUCOFEED 1 1/4 FR",
      "manufacturer": "H+S",
      "size": "1.25",
      "group": "M32",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    },
    {
      "id": "cable-sx-04172-b-60",
      "article": "84026748",
      "name": "SX 04172 B-60",
      "manufacturer": "H+S",
      "size": "Типоразмер уточняется",
      "group": "X9",
      "image": "../assets/configurator/cable-placeholder.svg",
      "minFrequencyMHz": null,
      "maxFrequencyMHz": null,
      "massGramsPerMeter": null,
      "minLengthMeters": 0.1,
      "maxLengthMeters": 100
    }
  ]
};
