const {connectors,cables}=window.NKT_CATALOG;
const state={a:null,b:null,cable:null,step:0,maxStep:0};
const $=id=>document.getElementById(id);
const unique=field=>[...new Set(connectors.filter(x=>x.id!=='OPEN').map(x=>x[field]))];
function fillSelect(id,items){$(id).insertAdjacentHTML('beforeend',items.map(x=>`<option value="${x}">${x}</option>`).join(''))}
fillSelect('typeA',unique('type'));fillSelect('typeB',unique('type'));fillSelect('cableType',cables.map(x=>x.name));

function compatible(conn,cable){return !conn||conn.id==='OPEN'||!cable||conn.group===cable.group}
function frequencyValue(){return $('frequency').value==='custom'?Number($('customFrequency').value)||0:Number($('frequency').value)||0}
function cableSupportsFrequency(cable){const f=frequencyValue();return !f||!((cable.minFrequencyMHz!=null&&f<cable.minFrequencyMHz)||(cable.maxFrequencyMHz!=null&&f>cable.maxFrequencyMHz))}
function itemImage(item,kind){const fallback=kind==='cable'?'../assets/configurator/cable-placeholder.svg':'../assets/configurator/connector-placeholder.svg';return `<img class="choice-image" src="${item.image||fallback}" alt="" loading="lazy" onerror="this.src='${fallback}'">`}
function renderConnectors(side){
 const p=side==='a'?'A':'B',type=$('type'+p).value,gender=$('gender'+p).value,shape=$('shape'+p).value,mount=$('mount'+p).value;
 let items=connectors.filter(x=>x.id!=='OPEN'&&(!type||x.type===type)&&x.gender===gender&&x.shape===shape&&x.mount===mount);if(side==='b')items.push(connectors.find(x=>x.id==='OPEN'));
 $('list'+p).innerHTML=items.map(x=>{const bad=!compatible(x,state.cable),detail=x.id==='OPEN'?'Открытый конец':`${x.manufacturer} · группа ${x.group}${x.article?` · арт. ${x.article}`:''}`;return `<button type="button" class="choice choice-product ${state[side]?.id===x.id?'selected':''}" data-side="${side}" data-id="${x.id}" ${bad?'disabled':''}>${itemImage(x,'connector')}<span><strong>${x.name}</strong><small>${detail}</small></span><b>${bad?'Несовместим':'Цена по запросу'}</b></button>`}).join('')||'<p class="empty-result">Для выбранного сочетания номенклатура не найдена.</p>';
}
function renderCables(){
 const name=$('cableType').value,selected=[state.a,state.b].filter(Boolean),f=frequencyValue();const items=cables.filter(x=>(!name||x.name===name)&&cableSupportsFrequency(x));
 $('listCable').innerHTML=items.map(x=>{const bad=selected.some(c=>!compatible(c,x));return `<button type="button" class="choice choice-product ${state.cable?.id===x.id?'selected':''}" data-cable="${x.id}" ${bad?'disabled':''}>${itemImage(x,'cable')}<span><strong>${x.name}</strong><small>${x.manufacturer} · ${x.size} · группа ${x.group}</small></span><b>${bad?'Несовместим':'Цена по запросу'}</b></button>`}).join('')||'<p class="empty-result">Нет кабелей, подходящих под выбранные параметры.</p>';
 const hasRanges=cables.some(x=>x.minFrequencyMHz!=null||x.maxFrequencyMHz!=null);$('frequencyFilterNote').textContent=hasRanges?(f?'Показаны кабели, подходящие для выбранной частоты.':'Укажите частоту, чтобы отфильтровать кабели.'):'Фильтр готов к работе; диапазоны частот ожидаются от инженеров.';
}
function selectConnector(side,id){state[side]=connectors.find(x=>x.id===id);const p=side==='a'?'A':'B';if(id!=='OPEN'){$('type'+p).value=state[side].type;$('gender'+p).value=state[side].gender;$('shape'+p).value=state[side].shape;$('mount'+p).value=state[side].mount}if(state.cable&&!compatible(state[side],state.cable))state.cable=null;renderAll()}
function selectCable(id){state.cable=cables.find(x=>x.id===id);$('cableType').value=state.cable.name;if(state.a&&!compatible(state.a,state.cable))state.a=null;if(state.b&&!compatible(state.b,state.cable))state.b=null;$('length').min=state.cable.minLengthMeters;$('length').max=state.cable.maxLengthMeters;renderAll()}
function lengthMeters(){return (Number($('length').value)||0)*({m:1,cm:.01,mm:.001}[$('lengthUnit').value])}
function lengthLabel(){return `${$('length').value||0} ${$('lengthUnit').selectedOptions[0].textContent}`}
function componentsValid(){return Boolean(state.a&&state.b&&state.cable&&frequencyValue()>0)}
function paramsValid(){const l=lengthMeters();return componentsValid()&&l>=state.cable.minLengthMeters&&l<=state.cable.maxLengthMeters}
function selectedTests(){return [...document.querySelectorAll('[name="test"]:checked')].map(x=>x.value)}
function connectorSymbol(x){if(!x||x.id==='OPEN')return '—';return x.shape==='Угловой'?'⌐':x.shape==='Панельный'?'▣':'↔'}
function calculatedWeight(){if(!state.a||!state.b||!state.cable||state.a.massGrams==null||state.b.massGrams==null||state.cable.massGramsPerMeter==null)return null;return state.a.massGrams+state.b.massGrams+state.cable.massGramsPerMeter*lengthMeters()}
function updateRequiredBlocks(){const l=lengthMeters(),lengthOk=Boolean(state.cable)&&l>=state.cable.minLengthMeters&&l<=state.cable.maxLengthMeters;const missing={connectorA:!state.a,cable:!state.cable||frequencyValue()<=0,connectorB:!state.b,assemblyParameters:!lengthOk};Object.entries(missing).forEach(([id,bad])=>{$(id).classList.toggle('required-missing',bad);$(id).setAttribute('aria-invalid',String(bad))})}
function goToStep(step){if(step>state.maxStep)return;state.step=step;document.querySelectorAll('.step-panel').forEach(x=>x.classList.toggle('active',Number(x.dataset.panel)===step));document.querySelectorAll('.stepper li').forEach((x,i)=>{x.classList.toggle('active',i===step);x.classList.toggle('completed',i<step);x.querySelector('button').disabled=i>state.maxStep});$('finalActions').hidden=step!==2;$('summaryGate').hidden=step===2;$('resetButton').hidden=step===2;updateSummary();document.querySelector('.workspace').scrollIntoView({behavior:'smooth',block:'start'})}
function updateNavigation(){const c=componentsValid(),p=paramsValid();document.querySelector('[data-next="1"]').disabled=!c;document.querySelector('[data-next="2"]').disabled=!p;if(c)state.maxStep=Math.max(state.maxStep,1);if(p)state.maxStep=Math.max(state.maxStep,2);document.querySelectorAll('.stepper button').forEach((b,i)=>b.disabled=i>state.maxStep)}
function updateSummary(){
 const complete=Boolean(state.a&&state.b&&state.cable),valid=paramsValid(),tests=selectedTests(),options=[];
 $('summaryA').textContent=state.a?`${state.a.name} · ${state.a.manufacturer}`:'—';$('summaryB').textContent=state.b?`${state.b.name} · ${state.b.manufacturer}`:'—';$('summaryCable').textContent=state.cable?`${state.cable.name} · ${state.cable.manufacturer}`:'—';$('summaryLength').textContent=lengthLabel();$('mapLength').textContent=lengthLabel();$('mapA').textContent=state.a?.name||'Не выбран';$('mapB').textContent=state.b?.name||'Не выбран';$('symbolA').textContent=connectorSymbol(state.a);$('symbolB').textContent=connectorSymbol(state.b);$('summaryFrequency').textContent=frequencyValue()?frequencyValue().toLocaleString('ru-RU')+' МГц':'—';
 if($('heatshrink').checked)options.push('Термоусадка');options.push(...tests);$('summaryOptions').textContent=options.join(', ')||'Без дополнительных опций';$('reviewMarking').textContent=`A: ${$('markingA').value.trim()||'без маркировки'}; кабель: ${$('markingCable').value.trim()||'без маркировки'}; B: ${$('markingB').value.trim()||'без маркировки'}`;$('reviewTests').textContent=tests.join(', ')||'Не выбрано';$('reviewExtraTests').textContent=$('extraTests').value.trim()||'Не указаны';$('reviewComment').textContent=$('comment').value.trim()||'Не указан';$('reviewDocuments').textContent=tests.length?`Спецификация сборки; ${tests.map(x=>'протокол: '+x.toLowerCase()).join('; ')}.`:'Спецификация сборки. Протоколы испытаний не выбраны.';
 const weight=calculatedWeight();$('reviewWeight').textContent=weight==null?'Недостаточно данных':`${Math.round(weight).toLocaleString('ru-RU')} г`;
 const status=$('status');let message='Выберите разъёмы, частоту и кабель';if(complete&&frequencyValue()<=0)message='Укажите рабочую частоту в разделе «Кабель»';else if(complete&&!valid)message='Проверьте длину сборки';else if(valid)message=state.step===2?'Готово к отправке':'Обязательные данные заполнены';status.className='status '+(valid?'valid':'warning');status.querySelector('span').textContent=message;
 $('assemblyCode').textContent=complete?`НКТ-${state.a.type}-${state.cable.name}-${state.b.type}-${String(Math.round(lengthMeters()*1000)).padStart(4,'0')}`:'Сборка не завершена';$('price').textContent=complete?'По запросу':'—';$('addToCart').disabled=!(valid&&state.step===2);$('cableDatasheet').disabled=!state.cable;updateRequiredBlocks();updateNavigation();history.replaceState(null,'','#'+new URLSearchParams({a:state.a?.id||'',c:state.cable?.id||'',b:state.b?.id||'',l:$('length').value,u:$('lengthUnit').value,f:frequencyValue()||'',s:state.step}).toString());
}
function renderAll(){renderConnectors('a');renderConnectors('b');renderCables();updateSummary()}
document.addEventListener('click',e=>{const c=e.target.closest('.choice');if(c?.dataset.side)selectConnector(c.dataset.side,c.dataset.id);if(c?.dataset.cable)selectCable(c.dataset.cable);const n=e.target.closest('[data-focus]');if(n)$(n.dataset.focus).scrollIntoView({behavior:'smooth',block:'center'});const next=e.target.closest('[data-next]');if(next&&!next.disabled)goToStep(Number(next.dataset.next));const prev=e.target.closest('[data-prev]');if(prev)goToStep(Number(prev.dataset.prev));const tab=e.target.closest('[data-step]');if(tab&&!tab.disabled)goToStep(Number(tab.dataset.step))});
['typeA','genderA','shapeA','mountA','typeB','genderB','shapeB','mountB'].forEach(id=>$(id).addEventListener('change',()=>renderConnectors(id.endsWith('A')?'a':'b')));$('cableType').addEventListener('change',renderCables);
function frequencyChanged(){if(state.cable&&!cableSupportsFrequency(state.cable))state.cable=null;renderCables();updateSummary()}
$('frequency').addEventListener('change',()=>{$('customFrequencyWrap').hidden=$('frequency').value!=='custom';frequencyChanged()});['length','lengthUnit','markingA','markingCable','markingB','heatshrink','extraTests','comment'].forEach(id=>$(id).addEventListener('input',updateSummary));$('customFrequency').addEventListener('input',frequencyChanged);document.querySelectorAll('[name="test"]').forEach(x=>x.addEventListener('change',updateSummary));
$('resetButton').addEventListener('click',()=>{state.a=state.b=state.cable=null;state.step=state.maxStep=0;$('configForm').reset();$('customFrequencyWrap').hidden=true;renderAll();goToStep(0)});$('printButton').addEventListener('click',()=>window.print());
$('addToCart').addEventListener('click',()=>{const request={code:$('assemblyCode').textContent,a:state.a,b:state.b,cable:state.cable,length:lengthLabel(),frequency:frequencyValue(),weightGrams:calculatedWeight(),marking:{a:$('markingA').value,cable:$('markingCable').value,b:$('markingB').value},tests:selectedTests(),extraTests:$('extraTests').value,comment:$('comment').value};localStorage.setItem('nkt-demo-cart',JSON.stringify(request));$('cartCount').textContent='1';$('cartContent').innerHTML=`<strong>${$('assemblyCode').textContent}</strong><p>${state.a.name} · ${state.cable.name} · ${state.b.name}<br>${lengthLabel()} · ${frequencyValue()} МГц</p><p>Все параметры сохранены вместе с конфигурацией.</p>`;$('cartDialog').showModal()});
$('cableDatasheet').addEventListener('click',()=>{if(!state.cable)return;$('infoContent').innerHTML=`<p><strong>${state.cable.name}</strong></p><p>${state.cable.manufacturer} · ${state.cable.size} · кабельная группа ${state.cable.group}</p><p class="data-note">Официальный технический файл пока не добавлен в проектные материалы.</p>`;$('infoDialog').showModal()});$('cartButton').addEventListener('click',()=>{$('cartContent').innerHTML=localStorage.getItem('nkt-demo-cart')?'В корзине сохранена одна демонстрационная конфигурация со всеми параметрами запроса.':'Корзина пока пуста.';$('cartDialog').showModal()});document.querySelectorAll('.dialog-close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
function loadHash(){const p=new URLSearchParams(location.hash.slice(1));if(p.get('a'))state.a=connectors.find(x=>x.id===p.get('a'))||null;if(p.get('b'))state.b=connectors.find(x=>x.id===p.get('b'))||null;if(p.get('c'))state.cable=cables.find(x=>x.id===p.get('c'))||null;if(p.get('l'))$('length').value=p.get('l');if(p.get('u'))$('lengthUnit').value=p.get('u');if(p.get('f')){$('frequency').value=[...$('frequency').options].some(x=>x.value===p.get('f'))?p.get('f'):'custom';if($('frequency').value==='custom'){$('customFrequency').value=p.get('f');$('customFrequencyWrap').hidden=false}}if(state.a){$('typeA').value=state.a.type;$('genderA').value=state.a.gender;$('shapeA').value=state.a.shape;$('mountA').value=state.a.mount}if(state.b&&state.b.id!=='OPEN'){$('typeB').value=state.b.type;$('genderB').value=state.b.gender;$('shapeB').value=state.b.shape;$('mountB').value=state.b.mount}if(state.cable)$('cableType').value=state.cable.name;$('cartCount').textContent=localStorage.getItem('nkt-demo-cart')?'1':'0';renderAll();state.maxStep=paramsValid()?2:componentsValid()?1:0;goToStep(Math.min(Number(p.get('s'))||0,state.maxStep))}loadHash();
